spring:
  application:
    name: design-patterns-dio
  datasource:
    url: jdbc:postgresql://postgres:ErNwfZoHHYhUOzxTDcHteyphzhnPvREf@caboose.proxy.rlwy.net:31580/railway
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
cors:
  allowed-origins: https://*.davisoares.com.br,https://davisfs21.github.io,http://localhost:8080,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,PATCH
security:
  jwt:
    secret-key: design-patterns-dio