spring:
  application:
    name: design-patterns-dio
  datasource:
    url: jdbc:postgresql://localhost:5432/tasktracker
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
cors:
  allowed-origins: https://*.davisoares.com.br,https://davisfs21.github.io,http://localhost:8080,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,PATCH
security:
  jwt:
    secret-key: design-patterns-dio